const combat = {
  desc: "These abilities increase your offensive, defensive and crossbow Skills. These Skills will appear red when equipped.",
  0: {
    "Fast Attack": {
      points: 5,
      pointsLimit: 5,
      desc: "Preform fast melee attacks with either sword",
    },
    "Strong Attack": {
      points: 5,
      pointsLimit: 5,
      desc: "Allows you to perform strong melee attacks which ignores enemy armor",
    },
    Defense: {
      points: 5,
      pointsLimit: 5,
      desc: "Wolf School defense techniques",
    },
    Marksmanship: {
      points: 5,
      pointsLimit: 5,
      desc: "Allows you to wield a light hand-held crossbow",
    },
    "Battle Trance": {
      points: 5,
      pointsLimit: 5,
      desc: "Blows landed during combat generate Adrenaline Points. Each Adrenaline Point increases weapon damage by 10%.",
    },
  },
  1: {
    "Muscle Memory": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Fast attack damage increase by 5%. Adrenaline Point gain: +1%",
    },
    "Strength Training": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Strong attack damage increase by 5%. Adrenaline Point gain: +1%",
    },
    "Arrow Deflection": {
      points: 0,
      pointsLimit: 3,
      desc: "Effect: Deflect arrows while parrying. Adrenaline Point gain: +1%",
    },
    "Lightning Reflexes": {
      points: 0,
      pointsLimit: 3,
      desc: "Effect: Time slowed by an additional 15% while aiming the crossbow. Adrenaline Point gain: +1%",
    },
    Resolve: {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Adrenaline Point loss upon taking damage is lowered by 20%. Adrenaline Point gain: +1%",
    },
  },
  2: {
    "Precise Blows": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Increases critical chance of fast attacks by 2% and their damage by 15%. Adrenaline Point gain: +1%",
    },
    "Crushing Blows": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Increases critical chance of strong attacks by 2% and their damage by 15%. Adrenaline Point gain: +1%",
    },
    "Fleet Footed": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Damage from hits received while dodging is reduced by 20%. Adrenaline Point gain: +1%",
    },
    "Cold Blood": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Each bolt that hits its target adds 0.04 Adrenaline Points. Adrenaline Point gain: +1%",
    },
    Undying: {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: When Vitality reaches 0, Adrenaline Points (if available) will be consumed to restore Vitality. The amount restored is based on the number of Adrenaline Points used. Adrenaline Point gain: +1%",
    },
  },
  3: {
    Whirl: {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Spinning attack that strikes all foes in the surrounding area. Maintaining the attack consumes Stamina and Adrenaline. Adrenaline Point gain: +1%",
    },
    Rend: {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Inflicts increased damage in proportion to used Endurance. Ignores enemy defense and increases critical chance by 10%. Adrenaline Point gain: +1%",
    },
    Counterattack: {
      points: 0,
      pointsLimit: 3,
      desc: "Effect: After a successful counterattack, the next attack deals +30% per skill level. Adrenaline Point gain: +1%",
    },
    "Anatomical Knowledge": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Increases crossbow critical hit chance by +5%. Adrenaline Point gain: +1%",
    },
    "Razor Focus": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect:Instantly gain 1 Adrenaline Point when entering combat. The Adrenaline Points generated by Sword blows are increased by 5%. Adrenaline Point gain: +1%",
    },
  },
  4: {
    "Crippling Strikes": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Fast attacks now also apply a Bleeding effect. Affected enemies lose 25 Vitality or Essence points per second. Duration: 5 seconds. Adrenaline Point gain: +1%",
    },
    "Sunder Armor": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Reduces enemy damage resistance by 5%. Adrenaline Point gain: +1%",
    },
    "Deadly Precision": {
      points: 0,
      pointsLimit: 2,
      desc: "Effect: Every point of adrenaline increases your instant kill chance by 1%. Adrenaline Point gain: +1%",
    },
    "Crippling Shot": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: Critical hits dealt with the crossbow disable monster special abilities for 5 seconds. Adrenaline Point gain: +1%",
    },
    "Flood of Anger": {
      points: 0,
      pointsLimit: 5,
      desc: "Effect: When casting a Sign, 3 Adrenaline Points (if available) will be consumed to upgrade the Sign to the highest level (unlocking all bonuses) and increases Sign intensity by 25%. Adrenaline Point gain: +1%",
    },
  },
};

export default combat;
